export const API_VERSION = "v1" as const;

export {
  ADMINISTRATION_CONTEXTS,
  type AdministrationContext,
  BATTERY_DOMAINS,
  BATTERY_ENGINE,
  BATTERY_PROFILE_MODEL,
  BATTERY_SESSION_STATUSES,
  type BatteryDefinition,
  type BatteryDomain,
  type BatterySection,
  type BatterySessionStatus,
  BREAK_MIN_MS,
  DEVICE_CLASSES,
  type DeviceClass,
  INPUT_MODES,
  type InputMode,
  ITEM_INSTANCE_STATUSES,
  ITEM_OUTCOMES,
  ITEM_ROLES,
  type ItemInstanceStatus,
  type ItemOutcome,
  type ItemRole,
  isBatteryDomain,
  isPowerDomain,
  POWER_DOMAINS,
  type PowerDomain,
  parseBatteryDefinition,
  RESPONSE_CODES,
  type ResponseCode,
  SECTION_STATUSES,
  type SectionStatus,
  VERSION_PIN_NONE,
} from "./battery";
export {
  buildItemPresentation,
  CLIENT_QUALITY_EVENT_KINDS,
  type ClientQualityEventKind,
  classifyResponse,
  type ItemPresentation,
  isClientQualityEventKind,
  parseItemPresentation,
  QUALITY_EVENT_KINDS,
  type QualityEventKind,
  type ResponseClassification,
  type ResponseClassificationInput,
  SERVER_QUALITY_EVENT_KINDS,
  SUBMISSION_GRACE_MS,
  shuffleForPresentation,
} from "./battery-session";
export {
  definitionEstimatedSeconds,
  definitionItemCount,
  type EngineDefinition,
  INSTRUMENT_ENGINES,
  type InstrumentEngineId,
  isInstrumentEngineId,
  parseEngineDefinition,
} from "./engines";
export {
  FIGURE_FILLS,
  FIGURE_MAX_COUNT,
  FIGURE_MAX_ELEMENTS,
  FIGURE_MAX_GRID,
  FIGURE_ROTATIONS,
  FIGURE_SHAPES,
  FIGURE_SIZES,
  type FigureCell,
  type FigureElement,
  type FigureFill,
  type FigureRotation,
  type FigureShape,
  type FigureSize,
  type FigureSpec,
  figureBlankCell,
  figureSignature,
  parseFigureSpec,
} from "./figure";
export {
  allItemsAnswered,
  type ClientLikertItem,
  isLikertCttScoring,
  isLikertDefinition,
  isLikertValue,
  LIKERT_ENGINE,
  type LikertCttBand,
  type LikertCttScoring,
  type LikertDefinition,
  type LikertItem,
  type LikertNormPoint,
  toClientLikertItem,
} from "./likert";
export {
  type ClientMcqItem,
  isMcqTimedDefinition,
  MCQ_TIMED_ENGINE,
  type McqAnswerValue,
  type McqTimedDefinition,
  type McqTimedItem,
  normalizeMcqAnswer,
  parseMcqAnswer,
  SUM_CORRECT_MODEL,
  toClientMcqItem,
} from "./mcq";
export {
  ACCURACY_POWER_MODEL,
  type ClientPowerChoice,
  type ClientPowerItem,
  DIFFICULTY_TIERS,
  type DifficultyTier,
  POWER_FORM_ENGINE,
  POWER_MAX_CHOICES,
  POWER_MCQ_ENGINE,
  POWER_MIN_CEILING_MS,
  POWER_MIN_CHOICES,
  POWER_MIN_SECTION_MS,
  type PowerChoice,
  type PowerFormDefinition,
  type PowerMcqItemContent,
  type PowerStimulus,
  parsePowerFormDefinition,
  parsePowerMcqItemContent,
  toClientPowerItem,
} from "./power-mcq";
export {
  type DomainQualityRule,
  parseQualityRuleSetDefinition,
  QUALITY_FLAGS,
  QUALITY_RULES_ENGINE,
  QUALITY_SEVERITIES,
  type QualityFlag,
  type QualityObservation,
  type QualityRuleSetDefinition,
  type QualitySeverity,
  resolveSectionEligibility,
  type SectionCovariates,
  type SectionEligibility,
  type SeverityRule,
  type ViewportMinimum,
} from "./quality-rules";
